import type { VeraConfig, VeraExtensionConfig } from "../../../src/config.ts";
import type { ModelSettingsPatch, ModelTurnSettings } from "../../../src/engine/model-settings.ts";
import type { AgentCatalogUpdate, AgentUpdate, UiRequestUpdate } from "../../../src/engine/protocol.ts";
import type { ClientExtensionRegistry } from "../../../src/extensions/client-registry.ts";
import type { DirectClientExtension } from "../../../src/extensions/client.ts";
import type { ExtensionCommandDescriptor } from "../../../src/extensions/commands.ts";
import type { WorkIndexSnapshot } from "../../../src/host/work-index.ts";
import type { AuthStorage } from "../../../src/providers/auth-storage.ts";
import type { VeraExperimentalTuiDocument } from "../../../src/sdk/experimental-tui.ts";
import type { VeraClientModelSettingsUpdateResult, VeraClientOneshotResult, VeraClientPickerResult, VeraExtensionDisposer } from "../../../src/sdk/extensions.ts";
import type { StandingNudge } from "../../../src/standing-nudges.ts";
import type { SessionSearchQuery } from "../../../src/store/session-search.ts";
import type { TuiActivityAnimation } from "../activity-pulse.ts";
import type { TuiAdmissionDialogState, TuiAdmissionDialogView } from "../admission-dialog.ts";
import type { TuiAgentClient } from "../agent-client.ts";
import type { TuiAppearance } from "../appearance.ts";
import type { TuiApprovalView } from "../approval.ts";
import type { TuiBodyFocusController } from "../body-focus.ts";
import type { TuiClientExtensionHostController } from "../client-extension-host.ts";
import type { TuiCommandPaletteState, TuiCommandPaletteView } from "../command-palette.ts";
import type { TuiCommandRegistry } from "../commands.ts";
import type { TuiComposer } from "../composer.ts";
import type { TuiDiagnosticsDialogState, TuiDiagnosticsDialogView } from "../diagnostics-dialog.ts";
import type { TuiClientExtensionReloadSnapshot, TuiDiagnosticsScope } from "../diagnostics.ts";
import type { DialStripState } from "../dials.ts";
import type { TuiExperimentalHost } from "../experimental-tui-host.ts";
import type { TuiFlightRecorder } from "../flight-recorder.ts";
import type { TuiHelpState, TuiHelpView } from "../help.ts";
import type { HomeClientOptions } from "../home-client.ts";
import type { HomeState, TuiHomeView } from "../home-screen.ts";
import type { TuiOnboardingView } from "../onboarding-screen.ts";
import type { WizardSession } from "../onboarding-wizard.ts";
import type { RuntimeCommand } from "./outrider-ops.ts";
import type { TuiHostedAgentSurface } from "../hosted-agent-surface.ts";
import type { TuiHostedPanePersistence } from "../hosted-pane-persistence.ts";
import type { TuiHostedSidebarAgent } from "../hosted-sidebar-agent.ts";
import type { JumpMenuState } from "../jump.ts";
import type { LinesView } from "../lines-view.ts";
import type { TuiDependencies, TuiExit } from "../main.ts";
import type { TuiNamePromptState, TuiNamePromptView } from "../name-prompt.ts";
import type { TuiPermissionsConfirmView } from "../permissions-confirm.ts";
import type { TuiPreferencesListState, TuiPreferencesListView } from "../preferences-list.ts";
import type { TuiProviderForgetConfirmView } from "../provider-forget-confirm.ts";
import type { TuiOverridesResetConfirmView } from "../overrides-reset-confirm.ts";
import type { ProviderHealthStatus } from "../provider-health.ts";
import type { TuiQuestionView } from "../question.ts";
import type { TuiQuote } from "../quote.ts";
import type { RenderCoalescer } from "../render-coalescer.ts";
import type { TuiRequestOptionsEditorState, TuiRequestOptionsEditorView } from "../request-options-editor.ts";
import { createTuiResumeOverlayView } from "../resume-overlay.ts";
import type { SearchOverlayState } from "../search-overlay.ts";
import type { TuiSecretPromptState, TuiSecretPromptView } from "../secret-prompt.ts";
import type { TuiSessionCloseConfirmView } from "../session-close-confirm.ts";
import type { TuiSessionTrashConfirmView } from "../session-trash-confirm.ts";
import type { TuiAnySettingsPickerState, TuiProviderFormState, TuiProviderFormView, TuiSettingsPickerState, TuiSettingsPickerView } from "../settings-picker.ts";
import type { TuiSidebar } from "../sidebar.ts";
import type { TuiExtensionsListState, TuiExtensionsListView } from "../extensions-list.ts";
import type { TuiStandingNudgesState, TuiStandingNudgesView } from "../standing-nudges.ts";
import type { TuiState, TuiTranscriptEntry } from "../state.ts";
import type { TuiThemeBinding } from "../theme-bindings.ts";
import type { TuiTheme, TuiThemeName } from "../theme.ts";
import type { TuiTimelinePickerState, TuiTimelinePickerView } from "../timeline-picker.ts";
import type { TuiTipState } from "../tips-store.ts";
import type { WorkTabState } from "../work-tab.ts";
import type { WorkspaceSidebarState } from "../workspace-sidebar.ts";
import type { BoxRenderable, CliRenderer, MarkdownRenderable, Renderable, ScrollBoxRenderable, SyntaxStyle, TextRenderable } from "@opentui/core";
import type { AsyncLocalStorage } from "node:async_hooks";

export type TuiAgentCatalog = {
    readonly selected: string;
    readonly agents: AgentCatalogUpdate["agents"];
    readonly notices: readonly string[];
};
export type TuiAgentCatalogRow = AgentCatalogUpdate["agents"][number];

export interface PoolChangeUndo {
    readonly action: "add" | "remove";
    readonly provider: string;
    readonly model: string;
    readonly poolName?: string;
}

export interface TuiRuntime {
    dependencies: TuiDependencies;
    client: TuiAgentClient;
    homeClientOptions: HomeClientOptions;
    flightRecorder: TuiFlightRecorder | undefined;
    configuredAppearance: TuiAppearance;
    renderer: CliRenderer;
    appearance: TuiAppearance;
    composerContentIndent: number;
    composerHorizontalInset: number;
    entrySpacing: { message: number; toolGroup: number; };
    copyText: (text: string) => Promise<void>;
    sessionTitle: string | undefined;
    mainHeaderVisible: boolean;
    sidebarSessionTitle: string | undefined;
    sidebarHeaderVisible: boolean;
    themeName: TuiThemeName;
    activityAnimation: TuiActivityAnimation;
    activityAnimationInterval: number | undefined;
    activityAnimationWidth: number | undefined;
    sidebarWidth: number | undefined;
    hostedPanePersistence: TuiHostedPanePersistence;
    theme: TuiTheme;
    state: TuiState;
    appendTranscriptRenderable: (
        node: Renderable,
    ) => VeraExtensionDisposer;
    openInspectDocument: (
        document: VeraExperimentalTuiDocument,
    ) => void;
    shuttingDown: boolean;
    clientSurfaceReady: boolean;
    transcriptSeeded: boolean;
    pendingTranscriptReseed: boolean;
    deferredKeymapNotices: string[];
    pendingBackNotice: string | undefined;
    pendingSessionSwitchNotice: string | undefined;
    experimentalTuiHost: TuiExperimentalHost;
    connectionFailed: boolean;
    connectionFailure: string | undefined;
    hostReconnectAttempted: boolean;
    agentFailedThisAttachment: boolean;
    statusNotice: string | undefined;
    statusNoticeVersion: number;
    modelPrefixPending?: boolean;
    requestedModelChanges: Map<string, { readonly subject: string; readonly patch: ModelSettingsPatch; readonly target: TuiAgentClient; }>;
    requestedPermissionChanges: Map<string, string>;
    abortRequested: boolean;
    pendingUiRequest: UiRequestUpdate | undefined;
    queuedUiRequests: UiRequestUpdate[];
    activeConfigurationRequest: {
        readonly requestId: string;
        readonly target: TuiAgentClient;
    } | undefined;
    queuedConfigurationRequests: Array<{
        readonly request: UiRequestUpdate;
        readonly target: TuiAgentClient;
    }>;
    followTranscriptAfterUiRequest: boolean;
    timelinePicker: TuiTimelinePickerState | undefined;
    settingsPicker: TuiAnySettingsPickerState | undefined;
    settingsPickerAgent: TuiAgentClient | undefined;
    pendingExtensionPicker: {
        readonly resolve: (result: VeraClientPickerResult) => void;
        readonly reject: (error: unknown) => void;
        readonly removeAbortListener: () => void;
    } | undefined;
    pendingExtensionSettings: Map<string, { readonly target: TuiAgentClient; readonly resolve: (result: VeraClientModelSettingsUpdateResult) => void; readonly reject: (error: unknown) => void; readonly removeAbortListener: () => void; }>;
    extensionSettingsListeners: Set<(settings: NonNullable<ModelTurnSettings | undefined>) => void>;
    extensionAgentTarget: AsyncLocalStorage<TuiAgentClient>;
    clientExtensionRegistry: ClientExtensionRegistry | undefined;
    keybindingOverlay: Readonly<Record<string, readonly string[]>>;
    announcedKeymapNotices: Set<string>;
    dialStrip: DialStripState | undefined;
    dialHistoryRequest?: { readonly requestId: string; readonly target: TuiAgentClient };
    autoModeAnimationStartedAt: number | undefined;
    autoModeAnimationTimer: ReturnType<typeof setInterval> | undefined;
    agentCatalog: TuiAgentCatalog | undefined;
    dismissedComposeSuggesters: Set<string>;
    pendingAgentCatalogs: Map<string, (catalog: TuiAgentCatalog | undefined) => void>;
    pendingSkillInvocations: Map<string, string>;
    messageInterceptPending: boolean;
    secretPrompt: TuiSecretPromptState | undefined;
    namePrompt: TuiNamePromptState | undefined;
    providerForm: TuiProviderFormState | undefined;
    requestOptionsEditor: TuiRequestOptionsEditorState | undefined;
    preferencesList: TuiPreferencesListState | undefined;
    standingNudges: TuiStandingNudgesState | undefined;
    standingNudgesProfileDirectory: string;
    standingNudgeRules: readonly StandingNudge[];
    preferencesListParent: TuiSettingsPickerState | undefined;
    extensionsList: TuiExtensionsListState | undefined;
    commandPalette: TuiCommandPaletteState | undefined;
    workTab: WorkTabState | undefined;
    workspaceSidebar: WorkspaceSidebarState | undefined;
    workspaceSidebarFocused: boolean;
    workspaceSidebarDocked: boolean;
    workspaceRailPreferred: number | undefined;
    workspaceRail: number | undefined;
    workspaceRailDragging: boolean;
    workspaceRailLaidOut: number | undefined;
    workspaceRailLaidOutColumns: number | undefined;
    workspaceSidebarDrawn: string | undefined;
    workspacePinnedIds: readonly string[];
    searchOverlay: SearchOverlayState | undefined;
    workIndex: WorkIndexSnapshot | undefined;
    jumpMenu: JumpMenuState | undefined;
    backOriginId: string | undefined;
    backOriginTitle: string | undefined;
    terminalFocused: boolean;
    stopWatchingWorkIndex: (() => void) | undefined;
    searchInFlight: boolean;
    pendingSearchTarget: {
        readonly sessionId: string;
        readonly entryId: string;
    } | undefined;
    searchLanding: {
        readonly sessionId: string;
        readonly entryId: string;
    } | undefined;
    queuedSearch: SessionSearchQuery | undefined;
    help: TuiHelpState | undefined;
    diagnosticsDialog: TuiDiagnosticsDialogState | undefined;
    documentDialog: (TuiDiagnosticsDialogState & {
        readonly renderMarkdown?: (columns: number) => string;
    }) | undefined;
    diagnosticsScope: TuiDiagnosticsScope;
    diagnosticsMenu: boolean;
    diagnosticsSessionPath: string | undefined;
    diagnosticsSessionIdentity: string | undefined;
    diagnosticsWorkerPid: number | undefined;
    diagnosticsSupervisorPid: number | undefined;
    diagnosticsProcessMemory: ReadonlyMap<number, number>;
    diagnosticsSessionPathResolved: boolean;
    diagnosticsGeneration: number;
    diagnosticsReportWidth: number | undefined;
    providerHealth: ProviderHealthStatus;
    providerHealthAbort: AbortController | undefined;
    providerHealthGeneration: number;
    doctorDialog: TuiDiagnosticsDialogState | undefined;
    doctorInspectionGeneration: number;
    extensionsDialog: TuiDiagnosticsDialogState | undefined;
    hostExtensionCommands: readonly ExtensionCommandDescriptor[];
    disposeHostExtensionCommands: () => void;
    extensionCommandsGeneration: number;
    disposeSkillCommands: () => void;
    skillCatalogRequestId: string | undefined;
    announcedSkillCommandNotices: Set<string>;
    confirmingFullAccess: boolean;
    confirmingFullAccessAgent: TuiAgentClient | undefined;
    pendingPoolName: {
        readonly requestId: string;
        readonly provider: string;
        readonly model: string;
        readonly label: string;
    } | undefined;
    pendingPoolChanges: Map<string, PoolChangeUndo>;
    pendingPoolUndos: Map<string, { readonly undo: PoolChangeUndo; readonly completesOnSettings: boolean; }>;
    poolChangeUndo: PoolChangeUndo | undefined;
    admissionDialog: TuiAdmissionDialogState | undefined;
    catalogRefreshes: Map<string, string>;
    catalogRefreshSweep: {
        readonly queue: readonly string[];
        index: number;
        readonly results: {
            provider: string;
            before: number;
            after?: number;
        }[];
        requestId?: string;
    } | undefined;
    modelVerification?: import("../model-verification.ts").VerificationRun;
    poolVerifySweep: {
        readonly queue: readonly { readonly provider: string; readonly model: string }[];
        readonly total: number;
        index: number;
        answered: number;
        requestId?: string;
    } | undefined;
    admissionReturnPicker: TuiSettingsPickerState | undefined;
    sessionTrashCandidate: {
        readonly sessionId: string;
        readonly label: string;
    } | undefined;
    sessionTrashPending: boolean;
    sessionCloseConfirm: boolean;
    providerForgetCandidate: {
        readonly providerId: string;
        readonly label: string;
        readonly pane: TuiSettingsPickerState | undefined;
    } | undefined;
    /** The levers a pending reset would clear, by label. Undefined when no reset is waiting on an answer. */
    overridesResetCandidate: readonly string[] | undefined;
    commandSuggestionIndex: number;
    commandSuggestionMoved: boolean;
    argumentSuggestions: readonly string[];
    extensionMentions: readonly string[];
    extensionAddressee: string | undefined;
    workingSince: number | undefined;
    phaseSince: number | undefined;
    activity: string;
    themeApplicationVersion: number;
    pendingThemePreview: ReturnType<typeof setTimeout> | undefined;
    clientGeneration: number;
    composeSurfaceGeneration: number;
    resumeListVersion: number;
    promptSubmitting: boolean;
    sessionSwitchPending: boolean;
    sessionSwitchActivity: string;
    sessionSwitchStartedAt: number | undefined;
    sessionSwitchOperation: string | undefined;
    sessionSwitchBufferedUpdates: AgentUpdate[];
    sessionSwitchClearingMain: boolean;
    extensionCommandPending: boolean;
    clientExtensionReloadPending: boolean;
    clientExtensionReload: TuiClientExtensionReloadSnapshot;
    extensionCommandActivity: string | undefined;
    sidebarPromptSubmitting: boolean;
    extensionCommandsLoading: boolean;
    skillCommandsLoading: boolean;
    runningBackgroundAgents: number;
    runningBackgroundAgentNames: readonly string[];
    currentAgentHasParent: boolean;
    stopWatchingBackgroundAgents: (() => void) | undefined;
    pendingSessionRename: {
        readonly requestId: string;

        readonly commandText?: string;
    } | undefined;
    pendingSidebarSessionRename: {
        readonly requestId: string;
        readonly commandText?: string;
    } | undefined;
    pendingOneshots: Map<string, { readonly resolve: (result: VeraClientOneshotResult) => void; readonly reject: (reason: Error) => void; }>;
    hostedSidebar: TuiHostedSidebarAgent;
    pendingSidebarContextNotice: {
        readonly agentId: string;
        readonly text: string;
    } | undefined;
    submitAfterImageAttachment: boolean;
    pendingImages: Array<{
        requestId: string;
        path?: string;
        id?: string;
        name?: string;
    }>;
    droppedImageReleases: Map<string, () => Promise<void>>;
    finished: { promise: Promise<TuiExit>; resolve: (value?: TuiExit | PromiseLike<TuiExit> | undefined) => void; reject: (reason?: any) => void; };
    disabledBuiltinExtensions: readonly string[];
    commandRegistry: TuiCommandRegistry;
    configuredClientExtensions: readonly VeraExtensionConfig[];
    hostedAgentSurface: TuiHostedAgentSurface;
    startConfiguredClientExtensionHost: (signal: AbortSignal, extensions?: readonly VeraExtensionConfig[], failureSink?: string[]) => Promise<ClientExtensionRegistry>;
    clientExtensionHost: TuiClientExtensionHostController;
    directClientExtensions: readonly DirectClientExtension[];
    markdownStyle: SyntaxStyle;
    transcript: ScrollBoxRenderable;
    JUMP_TO_BOTTOM_LABEL: string;
    jumpToBottomText: TextRenderable;
    jumpToBottom: BoxRenderable;
    SIDEBAR_JUMP_LABEL: " ↓ Jump to bottom ";
    sidebarJumpText: TextRenderable;
    sidebarJump: BoxRenderable;
    placeholder: TextRenderable;
    transcriptWorking: TextRenderable;
    transcriptEntryWindow: BoxRenderable;
    transcriptWindowTopSpacer: BoxRenderable;
    transcriptWindowBottomSpacer: BoxRenderable;
    entryNodes: (TextRenderable | MarkdownRenderable | BoxRenderable)[];
    entryNodeKinds: TuiTranscriptEntry["kind"][];
    entryNodeSources: WeakMap<BoxRenderable | TextRenderable | MarkdownRenderable, TuiTranscriptEntry>;
    materializedEntryStart: number;
    materializedEntryEnd: number;
    measuredEntryRows: number[];
    measuredEntryRowsWidth: number;
    pendingTranscriptScrollRestore: {
        readonly scrollTop: number;
        readonly atBottom: boolean;
    } | undefined;
    pendingTranscriptScrollAnchor: {
        readonly index: number;
        readonly offset: number;
    } | undefined;
    sidebarEntryNodes: (
        TextRenderable | MarkdownRenderable | BoxRenderable
    )[];
    sidebarEntryNodeKinds: TuiTranscriptEntry["kind"][];
    sidebarEntryGeneration: number;
    statusText: TextRenderable;
    activityHintText: TextRenderable;
    dialCardTitle: TextRenderable;
    dialCardHint: TextRenderable;
    dialCard: BoxRenderable;
    backgroundStatusText: TextRenderable;
    statusCard: BoxRenderable;
    workspaceBranch: { current(): string | undefined; stop(): void; };
    statusBand: BoxRenderable;
    hostedModeText: TextRenderable;
    placeRow: BoxRenderable;
    activityRow: BoxRenderable;
    tipsConfig: VeraConfig | undefined;
    tipsEnabled: boolean;
    tipState: TuiTipState;
    composerTip: string | undefined;
    workingLastRender: boolean;
    pickerTipKind: string | undefined;
    switchTipTurn: number;
    switchTipShown: boolean;
    composerTipText: TextRenderable;
    pendingQuote: TuiQuote | undefined;
    quoteText: TextRenderable;
    heldAddressText: TextRenderable;
    agentNoticeText: TextRenderable;
    queuedPromptText: TextRenderable;
    composer: TuiComposer;
    timelinePickerView: TuiTimelinePickerView;
    settingsPickerView: TuiSettingsPickerView;
    secretPromptView: TuiSecretPromptView;
    namePromptView: TuiNamePromptView;
    providerFormView: TuiProviderFormView;
    requestOptionsEditorView: TuiRequestOptionsEditorView;
    preferencesListView: TuiPreferencesListView;
    standingNudgesView: TuiStandingNudgesView;
    extensionsListView: TuiExtensionsListView;
    commandPaletteView: TuiCommandPaletteView;
    workTabView: LinesView;
    workspaceSidebarView: LinesView;
    searchOverlayView: LinesView;
    helpView: TuiHelpView;
    diagnosticsDialogView: TuiDiagnosticsDialogView;
    extensionsDialogView: TuiDiagnosticsDialogView;
    doctorDialogView: TuiDiagnosticsDialogView;
    documentDialogView: TuiDiagnosticsDialogView;
    permissionsConfirmView: TuiPermissionsConfirmView;
    admissionDialogView: TuiAdmissionDialogView;
    sessionTrashConfirmView: TuiSessionTrashConfirmView;
    sessionCloseConfirmView: TuiSessionCloseConfirmView;
    providerForgetConfirmView: TuiProviderForgetConfirmView;
    overridesResetConfirmView: TuiOverridesResetConfirmView;
    approvalView: TuiApprovalView;
    questionView: TuiQuestionView;
    commandSuggestionsText: TextRenderable;
    commandSuggestionsBox: BoxRenderable;
    jumpMenuText: TextRenderable;
    jumpMenuBox: BoxRenderable;
    composerMarginRows: number;
    agentNoticeRows: number;
    resumeOverlay: ReturnType<typeof createTuiResumeOverlayView>;
    jsonlCommandMode: boolean;
    modeToastText: TextRenderable;
    modeToast: BoxRenderable;
    modeToastVersion: number;
    verificationConsole: {
        readonly requestId: string;
        readonly subject: string;
    } | undefined;
    composerBox: BoxRenderable;
    composerStatusText: TextRenderable;
    composerRule: BoxRenderable;
    slashArgumentHint: TextRenderable;
    homeState: HomeState;
    homeTypedText: string | undefined;
    /** A prompt that reached submit with no provider behind it. It sits in the composer until the gates close. */
    onboardingPromptWaiting: boolean;
    /** The model-settings request the waiting prompt runs on, once onboarding has asked for it. */
    onboardingPromptRequest: string | undefined;
    homeSubmitPending: boolean;
    homeView: TuiHomeView;
    /** The first-run wizard, open only while a gate is still shut. */
    onboardingWizard: WizardSession | undefined;
    onboardingWizardView: TuiOnboardingView;
    onboardingWizardTimer: NodeJS.Timeout | undefined;
    needsYouChipWidth: number;
    composerTextRows: number;
    requestedComposerTextRows: number;
    bodyFocus: TuiBodyFocusController;
    upper: BoxRenderable;
    app: BoxRenderable;
    sidebar: TuiSidebar;
    overlayScrim: BoxRenderable;
    watchTerminalFocus: (chunk: Buffer | string) => void;
    stopWatchingTerminal: () => void;
    renderCoalescer: RenderCoalescer;
    statusTimer: NodeJS.Timeout;
    lastIdleEscapeAt: number | undefined;
    lastInputRecordAt: number;
    settingsSnapshotRetries: WeakMap<TuiAgentClient, number>;
    MAX_SETTINGS_SNAPSHOT_RETRIES: 5;
    recordedFocusSurface: string | undefined;
    authStorage: AuthStorage;
    connectingProviders: Set<string>;
    poolAdmissionAttempts: Map<string, { readonly provider: string; readonly model: string; readonly verify: boolean; readonly retry: boolean; }>;
    /** The provider whose model step is waiting for the new conversation's settings. */
    pendingOnboardingStep: string | undefined;
    /** The catalog refresh the model step has out, so its answer is told apart from every other one. */
    onboardingCatalogRefresh: string | undefined;
    /** The one real request that decides whether the last gate is clear. */
    onboardingVerification: { readonly requestId: string; readonly provider: string; readonly model: string; } | undefined;
    /** The install or start the wizard has out, held so a key can stop it. */
    onboardingRuntimeCommand: RuntimeCommand | undefined;
    themeBindings: readonly TuiThemeBinding[];
}
