// @ts-nocheck
const TUI_PARTITION = {
    "chrome.ts": ["applyTerminalTitle", "fallbackSessionTitle", "adoptFallbackSessionTitle", "refreshTerminalTitle", "toggleMainHeader", "toggleSidebarHeader", "readStandingNudgeRules", "adoptStandingNudgesState", "isSearchLanding", "markSearchLanding", "clearSearchLanding", "refreshKeymap", "coreHelpCommands", "registeredPaletteEntries", "workerFreeAction", "createMarkdownStyle", "clearSidebarEntryNodes", "closeSidebarPane", "composerSlotHeight", "setSurfaceBottomInsets", "setComposerMargin", "positionCommandSuggestions", "resizeComposer"],
    "agents-dials.ts": ["openExtensionAgent", "focusedAgentClient", "isCurrentExtensionComposeTarget", "focusedAgentState", "modelSettingsForAgent", "modelSettingsForOpenPicker", "dialPool", "dialCatalog", "committedDialPair", "openDials", "openAgentPicker", "describeAgentRow", "selectAgent", "requestAgentCatalog", "stopAutoModeAnimation", "startAutoModeAnimation", "closeDials", "closeTransientOverlaysForUiRequest", "commitDials", "setSidebarFocused", "focusedUiRequest", "focusedAbortRequested", "focusedAgentCanAbort", "composerIsAtLeftBoundary", "abortFocusedAgent", "releaseFocusedQueuedPrompts", "hostOwnsPromptQueue", "visibleMentions"],
    "sidebar-pane.ts": ["hostedAgentAddressing", "sidebarTranscriptWidth", "mainTranscriptWidth", "rememberOpenPaneGroup", "forgetPersistedAgentPane", "createTuiEntryNode", "renderSidebarAgent", "repaintSidebarForTheme", "handleSidebarAgentUpdate", "sidebarTheme"],
    "keypress.ts": ["applyTranscriptScroll", "handleKeypress"],
    "diagnostics-ops.ts": ["pressKey", "rowPointer", "requestAgentSettings", "retryMissingAgentSettings", "isSettingsRetryTrigger", "requestSessionSettings", "restorePersistedAgentPane", "diagnosticsSnapshot", "renderDiagnostics", "abortProviderHealthCheck", "paintDiagnosticsDialog", "startProviderHealthCheck", "noticeRepeatedModelFailure", "writeFailureReportFile"],
    "submit-prompt.ts": ["submitPrompt"],
    "prompt-routing.ts": ["leaveJsonlCommandMode", "refuseJsonlCommand", "availableCommandSuggestions", "availableCommandCompletion", "routeVisibleAgentPrompt", "attachImagesToSidebar", "offerMessageToExtensions", "attachPastedImage", "releaseDroppedImage"],
    "agent-updates.ts": ["receiveAgentUpdates"],
    "extension-bridge.ts": ["sendCommand", "requestExtensionModelSettingsUpdate", "settleExtensionModelSettings", "rejectPendingExtensionSettingsFor", "notifyExtensionSettings", "requireSidebarOwner", "resolvePooledModel", "requestExtensionOneshot", "requestExtensionPicker", "loadExtensionCommands", "supportsSkillCommands", "requestSkillCommands", "receiveSkillCatalog", "receiveSkillInvocation", "failPendingSkillInvocations"],
    "focus-switch.ts": ["activeOverlayFocus", "focusActiveSurface", "activeFlightSurface", "applyTimelineTransition", "withSessionSwitchDeadline", "recordSessionSwitchOutcome", "discardSwitchTarget", "leaveSwitchSource", "stopClientForShutdown", "discardCreatedSwitchTarget", "beginFork", "beginHostReconnect", "settleLostHost", "reportConnectionError"],
    "transcript-nodes.ts": ["tipContext", "tipPool", "takeTip", "transcriptEntryText", "transcriptEstimatedRows", "invalidateMeasuredEntryRows", "measureTranscriptEntryNode", "measureMaterializedTranscriptEntries", "transcriptEntryRows", "estimateTranscriptEntryRows", "estimatedTranscriptRows", "updateTranscriptEntryNode", "createTranscriptEntryNode", "destroyTranscriptEntryNode", "transcriptWindowChildIndex", "addTranscriptEntryNode", "updateTranscriptSpacers", "topmostVisibleTranscriptEntry", "applyTranscriptScrollAnchor", "captureTranscriptScrollAnchor", "transcriptFollowsBottom", "trimTranscriptWindow", "renderTranscriptEntries", "materializeEarlierTranscriptEntries", "materializeLaterTranscriptEntries", "nodeTranscriptRows", "evictTranscriptEntries", "maybeEvictTranscriptEntries", "setTranscriptWindow", "snapTranscriptWindowToTail", "setTranscriptWindowAround", "settleTranscriptScrollState", "maybeMaterializeEarlierTranscriptEntries", "maybeMaterializeLaterTranscriptEntries", "maybeSnapTranscriptWindowToTail"],
    "render-state.ts": ["renderState", "showSearchTarget", "drawWorkspaceSidebar", "refreshTimedSurfaces", "anyOverlayOpen", "shiftTranscriptEntrySlots", "reseedTranscriptNodes", "clearTranscriptNodes"],
    "model-pickers.ts": ["openReviewerMenu", "openReviewerPicker", "reviewerPatchFor", "reviewerToast", "openModelPicker", "modelRequestOptionsFacts", "modelPickerActionOptions", "isModelShortlisted", "refreshableProvidersOf", "catalogSizeOf", "currentModelAssignmentRows", "openModelAssignmentPicker", "bindModelAssignmentFromPicker", "configureDisplayPath", "configureFiles", "openConfigurePicker", "openConfigureEditor", "modelLevelFacts", "currentModelLevels", "openReasoningPicker", "openPermissionsPicker", "openThemePicker", "openPreferencesList", "openStandingNudges", "providerConnected", "openProviderEditForm", "openProviderPicker", "connectProvider"],
    "provider-forms.ts": ["forgetProvider", "forgetProviderCredential", "defaultLoginProvider", "openProviderEndpointForm", "openRequestOptionsEditor", "applyRequestOptionsEditorTransition", "applyProviderFormTransition", "applySecretPromptTransition", "applySessionRenamePromptTransition", "performSessionRename", "refreshSessionPicker", "openSettingsMenu", "openSettingsDestination", "openConfigurationRequiredRequest", "activateConfigurationRequiredRequest", "respondToConfigurationRequired", "openNextConfigurationRequiredRequest", "finishConfigurationPicker", "syncConfigurationRequiredRequest"],
    "palette-jump.ts": ["openSettingsMenuTarget", "runPaletteAction", "runStandalonePaletteAction", "runBack", "jumpMenuContentWidth", "closeJumpMenu", "renderJumpMenu", "runJumpTo"],
    "workspace-ops.ts": ["openJumpMenuOverlay", "openWorkTab", "focusWorkspaceSidebar", "openWorkspaceSidebar", "cycleLiveSession", "refreshWorkspaceSidebarRoster", "applyWorkspaceRail", "resizeWorkspaceRailAt", "closeWorkspaceSidebar", "runWorkspaceSidebarAction", "openResumePicker", "closeWorkSurfaces", "runWorkTabAction", "runSearchOverlayAction", "beginSearch", "openNamePrompt", "openSearchOverlay", "openCommandPalette", "openHelp"],
    "settings-picker-transition.ts": ["applySettingsPickerTransition", "closeSettingsPickerSurface"],
    "session-ops.ts": ["switchToClient", "destinationIsLive", "openSwitchDestination", "requestCloseSession", "beginParkToJsonl", "runHomeAction", "returnToHome", "refreshHomeSessions", "resumeJsonlView", "beginCreateSession", "beginSessionResume", "currentDraft", "beginSessionTrash", "performSessionTrash", "requestModelSettingsChange", "formatContextLimit", "retryPoolAdmission"],
    "pool-admission.ts": ["requestCatalogRefresh", "requestPoolAdmission", "dialogAdmission", "keptModels", "openCatalogRefreshScopePicker", "startCatalogRefreshSweep", "advanceCatalogRefreshSweep", "catalogRefreshSweepResult", "catalogRefreshSummary", "openPoolVerifyScopePicker", "startPoolVerifySweep", "advancePoolVerifySweep", "poolVerifySweepResult", "verifyModelInPicker", "closeAdmissionDialog", "requestPermissionsChange", "applySelectedTheme", "scheduleThemePreview"],
    "suggestions.ts": ["pooledModelNames", "activeCompletion", "renderCommandSuggestions", "activeComposeSuggester", "overlaysClearOfSuggestions", "finishStreamingAssistant", "copyTranscriptSelection", "announceCopy"],
    "notices.ts": ["showStatusNotice", "showModeToast", "clipToastMessage", "layoutModeToast", "showVerificationConsole", "verificationConsoleRows", "hideVerificationConsole", "dropSettledVerificationConsole", "liveVerificationConsole", "renderJumpToBottom", "renderSidebarJump", "renderPendingQuote", "renderHeldAddress", "paneHeaderText"],
    "render-status.ts": ["renderStatus"],
    "watchers.ts": ["watchBackgroundAgents", "watchWorkIndex", "applyWorkIndexSnapshot", "writeTerminal", "applyBackgroundAgents", "observeActivity", "finishThoughtPhase", "elapsedWorkingTime", "activityFrame", "emitExperimentalAgentEvent"],
};

const TUI_PARTITION_ORDER = [
    "chrome.ts",
    "agents-dials.ts",
    "sidebar-pane.ts",
    "keypress.ts",
    "diagnostics-ops.ts",
    "submit-prompt.ts",
    "prompt-routing.ts",
    "agent-updates.ts",
    "extension-bridge.ts",
    "focus-switch.ts",
    "transcript-nodes.ts",
    "render-state.ts",
    "model-pickers.ts",
    "provider-forms.ts",
    "palette-jump.ts",
    "workspace-ops.ts",
    "settings-picker-transition.ts",
    "session-ops.ts",
    "pool-admission.ts",
    "suggestions.ts",
    "notices.ts",
    "render-status.ts",
    "watchers.ts",
];

module.exports = { TUI_PARTITION, TUI_PARTITION_ORDER };
